Upgrade Tags system
grantrapp/grantr pull request #21
Opened 2022-09-16 12:57 UTC by svemat01

Use a dedicated dynamic tag system

Tags button in the admin menu
![](https://cdn.helgesson.dev/img/4b61a32685d5.webp)

Tags menu
![](https://cdn.helgesson.dev/img/d27d7c9095b0.webp)

Edit tag
![](https://cdn.helgesson.dev/img/e68dd9f33404.webp)

2022-09-16 13:25 UTC, svemat01 commented
Closes #12 #13 #14

2022-09-30 12:29 UTC, lucemans approved these changes
LGTM

2022-09-30 12:29 UTC, lucemans commented on backend/src/routes/tags/list.ts
> +// );
```suggestion
```

2022-09-30 12:29 UTC, lucemans commented on frontend/src/App.tsx
> +                                    element={<AdminTagEdit isNew />}
?

2022-09-30 12:31 UTC, lucemans requested changes
Pending changes...

2022-09-30 12:32 UTC, lucemans approved these changes
LGTM

2022-09-30 12:32 UTC, merged